config/routes.rb
Rails.application.routes.draw do
  resources :subsections
  devise_for :users

  root 'home#index'

  resources :settings, only: [:index]

  resources :schedules
  resources :employees
  resources :global_sections
  resources :users, only: [:show, :edit, :update]
end

app/models/employee.rb
class Employee < ApplicationRecord

  belongs_to :global_section

  def self.get_employee(employee_id)
    self.find(employee_id)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employee, only: [:edit, :update, :destroy]

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
    respond_to do |format|
      format.html { render partial: 'edit'}
    end
  end

  # POST /employees
  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to :settings, notice: 'Сотрудник успешно добавлен!'
    else
      redirect_to :settings, alert: 'Ошибка'
    end
  end

  # PATCH/PUT /employees/1
  def update
    if @employee.update(employee_params)
      redirect_to :settings, notice: 'Информация обновлена!'
    else
      redirect_to :settings, alert: 'Что-то пошло не так!'
    end
  end

  # DELETE /employees/1
  def destroy
    @employee.destroy
    redirect_to :settings, alert: 'Сотрудник удалён!'
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def employee_params
    params.require(:employee).permit(:name, :service_number, :global_section_id, :id, :morning, :evening, :duty, :work_overtime, :independence)

  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_edit.html.erb
<td colspan="6">
  <%= form_with model: @employee, local: true do |f| %>
    <div class="input-group">
      <%= f.text_field :service_number, class: "form-control", placeholder: "Табельный номер" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Имя сотрудника" %>

        У-<%= f.text_field :morning, class: "form-control", placeholder: "Утро" %>
        В-<%= f.text_field :evening, class: "form-control", placeholder: "Вечер" %>
        Д-<%= f.text_field :duty, class: "form-control", placeholder: "Дежурство" %>

      <%= f.check_box :work_overtime %>
      <%= f.check_box :independence %>

      <div class="input-group-append">
        <%= f.submit "Сохранить", :class => 'btn btn-primary' %>
        <%= link_to "Удалить", @employee, class: "btn btn-danger", method: :delete %>
      </div>
    </div>
  <% end %>
</td>

app/views/employees/_employee_form.html.erb
    <th scope="row">
      <%= @employee.service_number %>
    </th>

    <td>
      <%= @employee.name %>
    </td>

    <td class="text-right">
      <%= link_to image_tag('edit_icon.png', class: 'icon'), edit_global_section_path(@employee), id: ("edit_employee_#{@employee.id}"), remote: true %>
      <%= link_to image_tag('delete_icon.png', class: 'icon'), @employee, method: :delete %>
    </td>

app/views/employees/_new_employee_form.html.erb
<td colspan="6">
  <%= form_with model: @new_employee, id: "new-employee-form-#{@section.id}", class: 'form-inline', local: true do |f| %>
    <%= f.hidden_field :global_section_id %>
    <div class="input-group">
      <%= f.text_field :service_number, class: "form-control", placeholder: "Табельный номер", form: "new-employee-form-#{@section.id}" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Имя сотрудника", form: "new-employee-form-#{@section.id}" %>
      <div class="input-group-append">
        <%= f.submit "Добавить", :class => 'btn btn-primary', form: "new-employee-form-#{@section.id}" %>
      </div>
    </div>
  <% end %>
</td>

app/views/employees/_show.html.erb
    <th scope="row">
      <%= @employee.service_number %>
    </th>

    <td>
      <%= @employee.name %>
    </td>

    <td>
      <text>| У-<%= @employee.morning %> |</text>
      <text>В-<%= @employee.evening %> |</text>
      <text>Д-<%= @employee.duty %> |</text>
    </td>

    <td>
      <% if  @employee.work_overtime? %>
        <text>да</text>
      <% else %>
        <text>нет</text>
      <% end %>
    </td>

    <td>
      <% if  @employee.independence %>
        <text>да</text>
      <% else %>
        <text>нет</text>
      <% end %>
    </td>

    <td class="text-right">
      <%= link_to image_tag('edit_icon.png', class: 'icon'), edit_employee_path(@employee), id: ("edit-employee-link-#{@employee.id}"), "data-link-id" => "employee-#{@employee.id}", remote: true %>
      <%= link_to image_tag('delete_icon.png', class: 'icon'), @employee, method: :delete %>
    </td>