config/routes.rb
Rails.application.routes.draw do
  resources :subsections
  devise_for :users

  root 'home#index'

  resources :settings, only: [:index]

  resources :schedules
  resources :employees
  resources :global_sections
  resources :users, only: [:show, :edit, :update]
end

app/models/subsection.rb
class Subsection < ApplicationRecord
  belongs_to :global_section
end

app/controllers/subsections_controller.rb
class SubsectionsController < ApplicationController
  before_action :set_subsection, only: [:show, :edit, :update, :destroy]

  # GET /subsections
  def index
    @subsections = Subsection.all
  end

  # GET /subsections/1
  def show
  end

  # GET /subsections/new
  def new
    @subsection = Subsection.new
  end

  # GET /subsections/1/edit
  def edit
  end

  # POST /subsections
  def create
    @subsection = Subsection.new(subsection_params)

    if @subsection.save
      redirect_to settings_url, notice: 'Подсекция создана.'
    else
      redirect_to settings_url, alert: 'Что-то пошло не так'
    end
  end

  # PATCH/PUT /subsections/1
  def update
    if @subsection.update(subsection_params)
      redirect_to @subsection, notice: 'Subsection was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /subsections/1
  def destroy
    @subsection.destroy
    redirect_to settings_url, notice: 'Подсекция удалена.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subsection
      @subsection = Subsection.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def subsection_params
      params.require(:subsection).permit(:title, :global_section_id)
    end
end

app/helpers/subsections_helper.rb
module SubsectionsHelper
end

app/views/subsections/_new_subsection_form.html.erb
<%= form_with model: @subsection, local: true do |f| %>
  <%= f.label 'Добавить подсекцию:' %>
  <%= f.text_field @subsection.title, name: 'subsection[title]' %>
  <%= f.hidden_field @subsection.global_section_id, name: 'subsection[global_section_id]', value: "#{@section.id}" %>

  <%= f.submit %>
<% end %>

app/views/subsections/_show.html.erb
<td colspan="6">
  <p>Подсекции:</p>
  <% @section.subsections.each do |subsection| %>
    <p>
      <%= subsection.title %>
      <%= link_to image_tag('delete_icon.png', class: 'icon'), subsection, method: :delete %>
    </p>
  <% end %>
</td>

app/views/subsections/edit.html.erb
<h1>Editing Subsection</h1>

<%= render 'new_subsection_form', subsection: @subsection %>

<%= link_to 'Show', @subsection %> |
<%= link_to 'Back', subsections_path %>

app/views/subsections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subsections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subsections.each do |subsection| %>
      <tr>
        <td><%= subsection.name %></td>
        <td><%= link_to 'Show', subsection %></td>
        <td><%= link_to 'Edit', edit_subsection_path(subsection) %></td>
        <td><%= link_to 'Destroy', subsection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subsection', new_subsection_path %>

app/views/subsections/new.html.erb
<h1>New Subsection</h1>

<%= render 'new_subsection_form', subsection: @subsection %>

<%= link_to 'Back', subsections_path %>