config/routes.rb
Rails.application.routes.draw do
  resources :subsections
  devise_for :users

  root 'home#index'

  resources :settings, only: [:index]

  resources :schedules
  resources :employees
  resources :global_sections
  resources :users, only: [:show, :edit, :update]
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  before_save :set_working_days

  serialize :employees_data, Hash

  belongs_to :user

  def set_working_days
    set_base_days

  end

  def set_base_days
    employees_data.each do |section, employees|
      employees.each do |employee_id, employee|

        # Расстановка смен начинается с 3го числа.
        # 1е и 2е проставляются вручную на основании предыдущего графика.
        employee[:working_days].each do |day, type_and_hours|
          day = day.to_i

          if (employee[:working_days]["#{day}"][:hours] == "") && (day > 2)
            # Предыдущие два дня выходных или выходной и рабочий
            # вых-вых || вых-раб
            # Ставим рабочий
            # В остальных случаях оставляем пустым
            if ((employee[:working_days]["#{day - 1}"][:hours] == "") && (employee[:working_days]["#{day - 2}"][:hours] == "")) ||
                ((employee[:working_days]["#{day - 1}"][:hours] != "") && (employee[:working_days]["#{day - 2}"][:hours] == ""))
              employee[:working_days]["#{day}"][:hours] = "11"
            end
          end
        end
      end
    end
  end

  # Возвращает количество дней в месяце текущего графика
  def count_days_in_month
    Date.new(date.year, date.month, -1).day
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_schedules
  before_action :set_schedule, only: [:edit, :update, :destroy]



  # GET /schedules/new
  def new
    @schedule = Schedule.new(date: Date.today.next_month)
    @schedule.employees_data = helpers.new_schedule_employees_data
    @sections = current_user.global_sections

    render 'new'
  end

  def show
    redirect_to edit_schedule_url
  end

  # GET /schedules/1/edit
  def edit
    render 'edit'
  end

  # POST /schedules
  def create
    @schedule = current_user.schedules.new(schedule_params)

    if @schedule.save
      redirect_to edit_schedule_path(@schedule)
    else
      render :new, alert: 'Что-то не так'
    end
  end

  # PATCH/PUT /schedules/1
  def update
    if @schedule.update(schedule_params)
      redirect_to @schedule, notice: 'Schedule was successfully updated.'
    else
      render partial: 'edit'
    end
  end

  # DELETE /schedules/1
  def destroy
    @schedule.destroy
    redirect_to schedules_url, notice: 'Schedule was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_schedule
    @schedule = current_user.schedules.find(params[:id])
  end

  def set_schedules
    @schedules = current_user.schedules.all
  end

  # Разрешает определённые параметры и изменяет их, разделяя тип смены и часы
  def schedule_params
    params.require(:schedule).permit(:note_time_interval, :note_left, :note_center, :note_right, :date, :user_id, employees_data: {}).tap do |schedule_params|
      schedule_params[:employees_data].each do |section, employees|
        employees.each do |employee_id, employee|
          employee[:working_days].each do |day, value|
            value[:hours] = /\d+/.match(value[:type_and_hour]).to_s
            value[:type] = /[а-яА-Я]+/.match(value[:type_and_hour]).to_s
            value.delete(:type_and_hour)
          end
        end
      end
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  # Устанавливается основная структура хэша
  def new_schedule_employees_data
    employees_data = {}
    current_user.global_sections.each do |section|
      employees_data["#{section.title}"] = {}

      section.employees.each do |employee|
        employees_data["#{section.title}"]["#{employee.id}"] = {
            service_number: employee.service_number,
            name: "#{employee.name}",
            subsection: "",
            working_days: {}
        }

        @schedule.count_days_in_month.times do |day|
          employees_data["#{section.title}"]["#{employee.id}"][:working_days]["#{day+1}"] = {
              hours: "",
              type: ""
          }
        end
      end
    end

    employees_data
  end

  # Добавляет пустую строку в начало выпадающего списка с подсекциями
  # Метод map возвращает массив с подсекциями и метод unshift добавляет в его
  # начало пустую строку
  def subsections_for_employee(employee_id)
    Employee.get_employee(employee_id).global_section.subsections.map {|subsection| subsection.title}.unshift('')
  end
end

app/views/schedules/_form.html.erb
  <%= form_with model: @schedule, id: "new-schedule-form", local: true do |f| %>
    <%= f.hidden_field 'date', value: "#{@schedule.date}" %>
    <table class="schedule-table">
      <% serial_number = 1 %>
      <% @schedule.employees_data.each do |section, employees| %>
        <tr>
          <td rowspan="2">№</td>
          <td><%= section %></td>
          <td rowspan="2">Таб. №</td>
          <% @schedule.count_days_in_month.times do |day| %>
            <td><%= Russian.strftime(Date.new(@schedule.date.year, @schedule.date.month, day + 1), '%a') %></td>
          <% end %>
          <td colspan="2">Кол-во часов</td>
          <td rowspan="2">Сумма</td>
          <td rowspan="2">Закреплённая секция</td>
        </tr>

        <tr>
          <td>Ф.И.О.</td>
          <% @schedule.count_days_in_month.times do |day| %>
            <td><%= day + 1 %></td>
          <% end %>
          <td>дневных</td>
          <td>отпускных</td>
        </tr>

        <% employees.each do |employee_id, employee| %>
          <tr>
            <td><%= serial_number %></td>
            <td>
              <%= employee[:name] %>
              <%= f.hidden_field "employees_data[#{section}][#{employee_id}][name]", value: "#{employee[:name]}" %>
            </td>
            <td>
              <%= employee[:service_number] %>
              <%= f.hidden_field "employees_data[#{section}][#{employee_id}][service_number]", value: "#{employee[:service_number]}" %>
            </td>
            <% @schedule.count_days_in_month.times do |day| %>
              <td>
                <%= f.text_field "employees_data[#{section}][#{employee_id}][working_days][#{day + 1}][type_and_hour]", class: "day-input-field", value: "#{@schedule.employees_data["#{section}"]["#{employee_id}"][:working_days]["#{day + 1}"][:hours]}" + "#{@schedule.employees_data["#{section}"]["#{employee_id}"][:working_days]["#{day + 1}"][:type]}" %>
              </td>
            <% end %>
            <td></td>
            <td></td>
            <td></td>
            <td>
              <%= f.select "employees_data[#{section}][#{employee_id}][subsection]", subsections_for_employee(employee_id), selected: employee["subsection"] || '' %>
            </td>
          </tr>
          <% serial_number += 1 %>
        <% end %>
      <% end %>
    </table>
    <%= f.submit class: "button button-submit", id: "create-schedule-button" %>
  <% end %>

app/views/schedules/_menu.html.erb
<div class="schedule-menu">
  <div class="schedule-menu-header">
    <h4>ГРАФИКИ</h4>
  </div>
  <% @schedules.each do |schedule| %>
    <div class="schedule-menu-element">
      <%= link_to schedule.date.strftime("%m.%Y"), edit_schedule_path(schedule), id: "edit-schedule-link-#{schedule.id}" %>
    </div>
  <% end %>
  <%= link_to "Создать график", new_schedule_path, id: "new-schedule-link" %>
</div>

app/views/schedules/edit.html.erb
<%= render partial: 'menu' %>
<%= render partial: 'form' %>

app/views/schedules/index.html.erb
<%= render partial: 'menu' %>

<div class="schedule-area" data-block-id="schedule-area">
  <p>123</p>
</div>

app/views/schedules/new.html.erb
<%= render partial: 'menu' %>
<div class="schedule-area" data-block-id="schedule-area">
  <h3>Новый график на <%= @schedule.date.strftime('%m.%Y') %></h3>
  <%= render partial: 'form' %>
</div>