config/routes.rb
Rails.application.routes.draw do
  resources :subsections
  devise_for :users

  root 'home#index'

  resources :settings, only: [:index]

  resources :schedules
  resources :employees
  resources :global_sections
  resources :users, only: [:show, :edit, :update]
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">

  <%= link_to 'Главная', root_path, class: 'navbar-brand' %>
  <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to 'Графики', schedules_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Настройки', settings_path, class: 'nav-link' %></li>
    <% end %>
  </ul>

  <% if user_signed_in? %>
    <%= link_to (current_user.name? ? current_user.name : current_user.email), current_user, class: 'nav-item nav-link' %>
    <%= link_to 'Выйти', destroy_user_session_path, class: 'nav-item nav-link', method: :delete %>
  <% else %>
    <%= link_to 'Войти', new_user_session_path, class: 'nav-item nav-link' %> или <%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'nav-item nav-link' %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkSchedule</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <!-- Если есть специальный .js файл для этого контроллера, то подключаем его -->
  <% if File.exist?("#{Dir.pwd}/app/javascript/packs/#{controller_name}/#{controller_name}.js") %>
    <%= javascript_pack_tag 'application', "#{controller_name}/#{controller_name}" %>
  <% else %>
    <%= javascript_pack_tag 'application' %>
  <% end %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

</head>

<body>

<div class="wrapper">

  <%= render 'layouts/navbar' %>

  <% # Если текущий контроллер - schedules, оборачиваем в div с классом schedule-wrapper %>
  <% # Необходимо для флексов при работе с графиком %>
  <% if controller_name == 'schedules' %>
    <div class="schedule-wrapper">
      <%= yield %>
    </div>
  <% else %>
    <% if flash.notice %>
      <div id="notice" class="alert alert-success"><%= notice %></div>
    <% elsif flash.alert %>
      <div id="alert" class="alert alert-danger"><%= alert %></div>
    <% end %>

    <%= yield %>

  <% end %>
</div>
</body>
</html>